dongelek_root/car/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_view

from car.views import *



urlpatterns = [
    path('', index, name='home'),
    path('register/', register_request, name='register'),
    path('login/', login_request, name='login'),
    path('logout/',logout_request,name ='logout'),
    path('about/', about, name='about'),
    path('profile/', profile, name='profile'),
    path('add_car/', add_car, name='add_car'),
    path('brand/<slug:brand_slug>/', brand, name='brand'),
    path('car/<slug:car_slug>/', car, name='car'),
    path('city/<slug:city_slug>/', city, name='city'),
    path('rate-car/', rate_car, name='rate-car'),
    path('logout/',logout_request,name ='logout'),
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('your-cart', cart, name='your-cart'),
    path('send-email/', send_email, name='send-email'),
    path('delete-from-cart/', delete_from_cart, name='delete-from-cart'),
    path('delete-car/', delete_car, name='delete-car'),
    path('update-car/<slug:car_slug>/', update_car, name='update-car'),
    path('add-photos-car/<slug:car_slug>/', add_photos_car, name='add-photos-car'),
    path('searchbar/', searchbar, name='searchbar'),
    path('update-currency/', update_currency, name='update-currency'),
    path('purchase_pdf', purchase_pdf, name='purchase_pdf'),
    path('purchase/', purchase, name='purchase'),
    path('purchases/', purchases, name='purchases'),
    path('update-user/', update_user, name='update-user'),
    path('my-advertisements/', my_advertisements, name='my-advertisements'),

]

dongelek_root/dongelek/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from dongelek import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('car.urls')),
    path('profile/', include('chat.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dongelek_root/car/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
# Create your models here.
from django.urls import reverse

class Valute(models.Model):
    id = models.CharField(max_length=255, primary_key=True)
    num_code = models.IntegerField()
    char_code = models.CharField(max_length=10)
    nominal = models.IntegerField()
    name = models.CharField(max_length=255)
    value = models.DecimalField(max_digits=20, decimal_places=10)
    previous = models.DecimalField(max_digits=20, decimal_places=10)
class City(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('city', kwargs={'city_slug': self.slug})
    def get_amount_cars(self):
        count = 0;
        cars = Car.objects.filter(city=self.pk,isSold=False)
        for car in cars:
            count = count + 1
        return count
    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cities'

class Brand(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=50, unique=True, db_index=True)
    logo = models.ImageField(upload_to='car/brand')

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('brand', kwargs={'brand_slug': self.slug})
    class Meta:
        verbose_name = 'Brand'
        verbose_name_plural = 'Brands'


class Car(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    year = models.IntegerField()
    engine_capacity = models.DecimalField(max_digits=4, decimal_places=2)
    run = models.BigIntegerField()
    color = models.CharField(max_length=255)
    description = models.TextField()
    time_created = models.DateField(auto_now_add=True)
    time_updated = models.DateField(auto_now=True)
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    seller = models.ForeignKey(User, on_delete=models.CASCADE)
    main_image = models.ImageField(upload_to='car/main_image/%Y/%m/%d')
    price = models.BigIntegerField()
    isSold = models.BooleanField(default=False)

    def __str__(self):
        return self.name

    def get_amount_ratings(self):
        return len(Ratings.objects.filter(car=self))
   
    def get_absolute_url(self):
        return reverse('car', kwargs={'car_slug': self.slug})
   
    def get_average_rating(self):
        ratings = Ratings.objects.filter(car=self)
        if len(ratings) == 0:
            return 0
        sum = 0
        for rating in ratings:
            sum += rating.rating
        return round(sum / len(ratings), 2)
    
    def get_comments(self):
        comments = Comments.objects.filter(car=self)
        return len(comments)

    def get_count_rating(self):
        ratings = Ratings.objects.filter(car=self)
        return len(ratings)

    def get_visiters(self):
        visits = Visits.objects.filter(car=self)
        return len(visits)

    def get_carts(self):
        carts = Cart.objects.filter(car=self)
        return len(carts)
    
    class Meta:
        verbose_name = 'Car'
        verbose_name_plural = 'Cars'

    def get_absolute_update_url(self):
        return reverse('update-car', kwargs={'car_slug': self.slug})
    def get_absolute_add_url(self):
        return reverse('add-photos-car', kwargs={'car_slug': self.slug})

class Car_photos(models.Model):
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='car/images/%Y/%m/%d')

class Comments(models.Model):
    comment = models.TextField()
    date = models.DateField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Comment'
        verbose_name_plural = 'Comments'

class Visits(models.Model):
    date = models.DateField(auto_now_add=True)
    visiter = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'Visit'
        verbose_name_plural = 'Visits'

class Ratings(models.Model):
    date = models.DateField(auto_now_add=True)
    rater = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0,
            validators=[
                MaxValueValidator(5),
                MinValueValidator(0)
            ])
    class Meta:
        verbose_name = 'Rating'
        verbose_name_plural = 'Ratings'

class Cart(models.Model):
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

class Purchase(models.Model):
    date = models.DateField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

dongelek_root/car/views.py
from cProfile import run
from django.contrib import messages
from django.shortcuts import *
from django.http import HttpRequest, JsonResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from car.models import *
from .forms import *
from django.core.mail import send_mail
from dongelek.settings import EMAIL_HOST_USER
import os.path
import requests
import json
from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter


from urllib.request import urlopen
from django.shortcuts import render,redirect


# Create your views here.

menu = [
    {'title': "About site",
     'url_name': 'about'},
]
valutes = Valute.objects.all()


# Index home page
def index(request):
    brands = Brand.objects.all()
    cities = City.objects.all()
    context = {
        'title': "Main Page",
        'menu': menu,
        'brands': brands,
        'cities': cities,
        'valutes': valutes,
    }
    return render(request, 'car/index.html', context)

def update_currency(request):
    url = 'https://www.cbr-xml-daily.ru/daily_json.js'
    response = urlopen(url)
    data_json = json.loads(response.read())
    for v_id, v_info in data_json['Valute'].items():
        Valute.objects.filter(id=v_info["ID"]).update(id=v_info["ID"], num_code=v_info["NumCode"],
                              char_code=v_info["CharCode"], nominal=v_info["Nominal"],
                              name=v_info["Name"], value=v_info["Value"], previous=v_info["Previous"])
    return redirect('profile')
# Registration 
def register_request(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect('login')
    return render(request, 'car/register.html', {
        'form': form
    })


# Login
def login_request(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.error(request, "Invalid username or password")
            return redirect('login')

    else:
        return render(request, 'car/login.html')

    # Logout


def logout_request(request):
    logout(request)
    return redirect('home')


# About
def about(request):
    context = {
        'title': "About",
        'menu': menu,
        'valutes': valutes,
    }
    return render(request, 'car/about.html', context)


# Profile
def profile(request):
    cars = Car.objects.filter(seller=request.user)
    context = {
        'title': 'My profile',
        'menu': menu,
        'cars': cars,
        'valutes': valutes,
        'seller':request.user
    }
    return render(request, 'car/profile.html', context)


# add_car
def add_car(request):
    if request.method == 'POST':
        form = AddCar(request.POST, request.FILES)
        if form.is_valid():
            try:
                Car.objects.create(**form.cleaned_data, seller=request.user)
                return redirect('home')
            except:
                form.add_error(None, "There are some errors")
    else:
        form = AddCar()
    context = {
        'title': "Add a new ad",
        'menu': menu,
        'form': form,
        'valutes': valutes,
    }
    return render(request, 'car/addCar.html', context)


def brand(request, brand_slug):
    chosen_brand = Brand.objects.get(slug=brand_slug)
    cars = Car.objects.filter(brand_id=chosen_brand.pk,isSold=False)
    if request.method == 'GET':
        form = request.GET.get('sort')
        if form == 'priceup':
            cars = cars.order_by('price')
        elif form == 'pricedown':
            cars = cars.order_by('-price')
        elif form == 'news':
            cars = cars.order_by('-time_created')
        elif form == 'olds':
            cars = cars.order_by('time_created')
    context = {
        'title': chosen_brand.name,
        'menu': menu,
        'cars': cars,
        'valutes': valutes,
        'brand': chosen_brand,
        
    }

    return render(request, 'car/brand.html', context)


def city(request, city_slug):
    city = City.objects.get(slug=city_slug)
    cars = Car.objects.filter(city_id=city.pk,isSold=False)
    if request.method =='GET':
        form = request.GET.get('sort')
        if form == 'priceup':
            cars = cars.order_by('price')
        elif form == 'pricedown':
            cars = cars.order_by('-price')
        elif form == 'news':
            cars = cars.order_by('-time_created')
        elif form == 'olds':
            cars = cars.order_by('time_created')
    context = {
        'valutes': valutes,
        'title': city.name,
        'menu': menu,
        'cars': cars,
        'brand': city,
    }
    return render(request, 'car/brand.html', context)

def cart(request):
    cars = Cart.objects.filter(user=request.user)
    context = {
        'valutes': valutes,
        'title': 'Your cart',
        'menu': menu,
        'cars': cars,
    }
    return render(request, 'car/cart.html', context)


def car(request, car_slug):
    car = Car.objects.get(slug=car_slug)
    photos = Car_photos.objects.filter(car=car)
    seller = User.objects.get(pk=car.seller.pk)
    if request.user.is_authenticated and car.seller != request.user:
        Visits(car=car, visiter=request.user).save()
    comments = Comments.objects.filter(car=car).order_by('-pk')
    if request.method == 'POST':
        form = AddComment(request.POST)
        if form.is_valid():
            try:
                Comments.objects.create(**form.cleaned_data, author=request.user, car=car)
                request.POST = None
                return redirect(car.get_absolute_url())
            except:
                form.add_error(None, "There are some errors")
        form = AddComment()
    else:
        form = AddComment()
    context = {
        'title': car.name,
        'valutes': valutes,
        'menu': menu,
        'form': form,
        'seller': seller,
        'comments': comments,
        'car': car,
        'photos': photos,
    }
    cart = Cart.objects.filter(car=car.pk, user=request.user.pk)
    if len(cart) > 0:
        context['cart'] = True
    else:
        context['cart'] = False
    if car.get_average_rating() == 0:
        context['rating'] = False
    else:
        context['rating'] = car.get_average_rating()
    return render(request, 'car/car.html', context)


def rate_car(request):
    if request.method == 'POST':
        rating = request.POST.get('rating')
        car_id = request.POST.get('car')
        car = Car.objects.get(pk=car_id,isSold=False)
        rater = request.user
        Ratings.objects.filter(car=car, rater=rater).delete()
        Ratings.objects.create(rating=rating, car=car, rater=rater).save()
        return JsonResponse({'success': 'true', 'score': rating}, safe=False)
    return JsonResponse({'success:': 'false'})


def add_to_cart(request):
    if request.method == 'POST':
        car_id = request.POST.get('car_basket')
        car = Car.objects.get(pk=car_id,isSold=False)
        user = request.user
        Cart.objects.filter(car=car, user=user).delete()
        Cart.objects.create(car=car, user=user).save()
        return JsonResponse({'success': 'true'})
    return JsonResponse({'success:': 'false'})


def delete_from_cart(request):
    if request.method == 'POST':
        car_id = request.POST.get('car_basket')
        car = Car.objects.get(pk=car_id,isSold=False)
        user = request.user
        Cart.objects.filter(car=car, user=user).delete()
        return JsonResponse({'success': 'true'})
    return JsonResponse({'success:': 'false'})


def delete_car(request):
    if request.method == 'POST':
        car_id = request.POST.get('car')
        car = Car.objects.filter(pk=car_id,isSold=False).delete()
        print(car)
        return JsonResponse({'success': 'true'})
    return JsonResponse({'success:': 'false'})


def send_email(request):
    if request.method == 'POST':
        car_id = request.POST.get('car_interested')
        car = Car.objects.get(pk=car_id,isSold=False)
        seller_email = request.POST.get('seller_email')
        seller_username = request.POST.get('seller_username')
        subject = 'Someone is interested to your car '
        message = request.user.username + " ( " + request.user.email + " )" + " is interested  to your " + str(car)
        send_mail(subject, message,
                  EMAIL_HOST_USER, [seller_email], fail_silently=False)
        subject = "From Dongelek.kz"
        message = "You've interested to " + str(car) + ". Wait answer from " + seller_username
        send_mail(subject, message,
                  EMAIL_HOST_USER, [request.user.email], fail_silently=False)
        return JsonResponse({'success': 'true'})
    return JsonResponse({'success:': 'false'})


def update_car(request, car_slug):
    car = Car.objects.get(slug=car_slug)
    if request.method == 'POST':
        form = AddCar(request.POST, request.FILES)
        if form.is_valid():
            try:
                os.remove(car.main_image.path)
                car.name = form.cleaned_data['name']
                car.slug = form.cleaned_data['slug']
                car.year = form.cleaned_data['year']
                car.engine_capacity = form.cleaned_data['engine_capacity']
                car.run = form.cleaned_data['run']
                car.color = form.cleaned_data['color']
                car.city = form.cleaned_data['city']

dongelek_root/car/templates/car/about.html
{% extends 'car/base.html' %}
{% block scripts %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
{% endblock %}
{% block content %}
    <body>

<div id="tooplate_wrapper">

	<div id="tooplate_header">
        <div id="site_title"><h1><a href="#">Dongelek.kz</a></h1></div>


    <div id="tooplate_main">

		<div id="tooplate_content">

      		<div class="col_w900">
            	<h2>About Us</h2>
                <p>Name of the our group is Key To Life. In our group we have 5 members. Whose name is Zangar , Yernar , Asset , Marlen , Dimash.  </p>


				<h2>About Site</h2>
                <p>We want to do this site to look alike to <a href="https://kolesa.kz/" rel="nofollow"><strong>kolesa</strong></a> , but on the other case we want to do something special, and this site is the result of out work.</p>
                <h2>We in social sites</h2>
				<ul class="tooplate_list">
                    <li><a href="https://kolesa.kz/" rel="nofollow"><strong>Zangar</strong></a> </li>
                    <li><a href="https://www.instagram.com/khsndmsh/" rel="nofollow"><strong>Dimash</strong></a>(in instagram)</li>
                    <li><a href="https://kolesa.kz/" rel="nofollow"><strong>Asset</strong></a></li>
                    <li><a href="https://kolesa.kz/" rel="nofollow"><strong>Marlen</strong></a></li>
                    <li><a href="https://www.instagram.com/yernare/" rel="nofollow"><strong>Yernar</strong></a>(in instagram)</li>
                </ul>

                <div class="cleaner"></div>
            </div>

            <div class="cleaner"></div>
            </div>

        </div>

    </div>

    <div id="tooplate_footer">
    	Copyright © 2048     <a href="https://bil.edu.kz/" rel="nofollow"><strong>Key To Life</strong></a>
	</div>

</div>
</body>
{% endblock %}

dongelek_root/car/templates/car/addCar.html
{% extends 'car/base.html' %}
{% load static %}
{% block scripts %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/addCar.css' %}">
{% endblock %}

{% block content %}
    <div class="form_container">
        <div class="title">
            Add a new Car
        </div>
        <form action="{% url 'add_car' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="form_attribute_container full">
                    <span>Name*</span>
                    <input type="text" name="name" maxlength="255" required id="id_name">
                </div>
                <div class="form_attribute_container full">
                    <span>Slug*</span>
                    <input type="text" name="slug" maxlength="255" required id="id_slug">
                </div>
                <div class="form_attribute_container half">
                    <span>Year*</span>
                    <input type="number" name="year" required id="id_year">
                </div>
                <div class="form_attribute_container half">
                    <span>Run*</span>
                    <input type="number" name="run" required id="id_run">
                </div>
                <div class="form_attribute_container half">
                    <span>Engine Capacity*</span>
                    <input type="number" name="engine_capacity" required id="id_engine_capacity" step=".01">
                </div>
                <div class="form_attribute_container half">
                    <span>Color*</span>
                    <input type="text" name="color" maxlength="255" required id="id_color">
                </div>
                <div class="form_attribute_container half">
                    <span>City*</span>
                    {{form.city}}
                </div>
                <div class="form_attribute_container half">
                    <span>Brand*</span>
                    {{form.brand}}
                </div>
                <div class="form_attribute_container half">
                    <span>Price*</span>
                    <input type="number" name="price" required id="id_price">
                </div>
                <div class="form_attribute_container half">
                    <span>Main Image*</span>
                    <label for="id_main_image">Choose Image</label>
                    <input type="file" name="main_image" accept="image/*" required id="id_main_image" value="{{car.image}}">
                </div>
                <div class="full description_container">
                    <span>Description*</span>
                    <textarea name="description" id="id_description" cols="0" rows="10" placeholder="Description"></textarea>
                </div>
            <button type="submit">Add</button>
        </form>
    </div>

{% endblock %}

dongelek_root/car/templates/car/base.html
{% load static %}
{% load car_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <!--Footer -->
    <link type="text/css" rel="stylesheet" href="{% static 'css/footer.css' %}">
    <!-- End Footer -->

    <link type="text/css" rel="stylesheet" href="{% static 'css/header.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{% static 'js\valute.js' %}" defer></script>
    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@trevoreyre/autocomplete-js/dist/style.css"/>
    {% block scripts %}
    {% endblock %}
    <style>
        .search_container input{
            background-image: url("{% static 'images/search_icon.png' %}");
            background-repeat:no-repeat;
            background-size: 30px;
            background-position: 3px;
        }
    </style>
</head>
<body>

    {% block mainmenu %}

        <div class="header">

            <a href="{% url 'home' %}">
                <div class="header_container">
                    <img id="logo" src="{% static 'images/logo.png' %}" height="40px">
                    <div class="logo_name">
                        Dongelek.kz
                    </div>
                </div>
            </a>

            <div class="header_container">
                {% for m in menu %}
                    <a href="{% url m.url_name %}">
                        <div class="menu">{{m.title}}</div>
                    </a>
                {% endfor %}
                {% if request.user.is_authenticated %}
                    <a href="{% url 'add_car' %}">
                        <div class="menu">Add an add</div>
                    </a>
                    <a href="{% url 'your-cart' %}">
                        <div class="menu">Your cart</div>
                    </a>
                    <a href="{% url 'purchases' %}">
                        <div class="menu">My purchases</div>
                    </a>
                {% endif %}
            </div>
            <div class="header_container last_header_container">

                <select name="currency" id="currency_select" onchange="changeValute()">
                    <option value="none" selected disabled hidden>Select a valute</option>
                    {% for valute in valutes %}
                        <option value='{"value":{{ valute.value }}, "nominal":{{ valute.nominal }}, "name":{{valute.char_code}}}' nominal="{{ valute.nominal }}" name="{{ valute.char_code }}">{{ valute.char_code }}</option>
                    {% endfor %}
                </select>

                <!-- user aty wygyp turady -->
                {% if request.user.is_authenticated %}
                    <a href="{% url 'logout'%}">
                        <div class="menu">Logout</div>
                    </a>
                    <a href="{% url 'profile' %}">
                        <div class="menu">{{user.username}}</div>
                    </a>
                {% else %}
                    <a href="{% url 'login' %}">
                        <div class="menu">Log in</div>
                    </a>
                    <a href="{% url 'register' %}">
                        <div class="menu">Register</div>
                    </a>
                {% endif %}
            </div>
        </div>
        <center>
            <div class="search_container">
                <form action="{% url 'searchbar' %}" method="get">
                    <input type="text" name="search" placeholder="Search..." value="{{search}}"/>
                    <button type="submit">Search</button>
                </form>
            </div>
        </center>

    {% endblock mainmenu %}


    <div class="content">
        {% block content %}
        {% endblock %}
    </div>
<footer class="footer-distributed">
    <div class="footer-left">
        <h3>Dongelek.<span>kz</span></h3>
        <p class="footer-links" ><a href="{% url 'home' %}">Home</a>
            ·<a href="{% url 'about' %}">About</a>
            ·<a href="{% url 'your-cart' %}">Cart</a>
            ·<a href="{% url 'purchases' %}">Purchase</a>
            ·<a href="{% url 'profile' %}">Profile</a>
            ·<a href="{% url 'send-email' %}">Contact</a>
        </p>
        <p class="footer-company-name">dongelek.kz &copy; 2022</p>
    </div>
    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"><img src="{% static 'images/location.png' %}" width="30px" height="30px"></i>
            <p><span>21 Revolution Street</span> Almaty, Kazakhstan</p>
        </div>
        <div>
            <i class="fa fa-phone"><img src="{% static 'images/call.png' %}" width="30px"></i>
            <p>+7 777 123 4567</p>
        </div>
        <div>
            <i class="fa fa-envelope"><img src="{% static 'images/message.png' %}" width="30px"></i>
            <p><a href="mailto:support@company.com">contact@webdevtrick.com</a></p>
        </div>
    </div>

    <div class="footer-right">
        <p class="footer-company-about">
            <span>About the company</span>
            Web Dev Trick is a blog for web designers, graphic designers, web developers &amp; SEO Learner.
        </p>

        <div class="footer-icons">
            <a href="#"><img src="{% static 'images/Meta.png' %}" width="30px"><i class="fa fa-facebook"></i></a>
            <a href="#"><img src="{% static 'images/twitter.png' %}" width="30px"><i class="fa fa-twitter"></i></a>
            <a href="#"><img src="{% static 'images/linkedin.png' %}" width="30px"><i class="fa fa-linkedin"></i></a>
            <a href="https://github.com/sdu-be-22/dongelek.kz"><img src="{% static 'images/GitHub.png' %}" width="30px"><i class="fa fa-github"></i></a>
        </div>

    </div>
</footer>
</body>
</html>

dongelek_root/car/templates/car/update.html
{% extends 'car/base.html' %}
{% load static %}
{% block scripts %}
    <link type="text/css" rel="stylesheet" href="{% static 'css/addCar.css' %}">
{% endblock %}

{% block content %}
    <div class="form_container">
        <div class="title">
            Update Car Information
        </div>
        <form method="POST" action="{{car.get_absolute_update_url}}" enctype="multipart/form-data">
            {% csrf_token %}
                <div class="form_attribute_container full">
                    <span>Name*</span>
                    <input type="text" name="name" maxlength="255" required id="id_name" value="{{car.name}}">
                </div>
                <div class="form_attribute_container full">
                    <span>Slug*</span>
                    <input type="text" name="slug" maxlength="255" required id="id_slug" value="{{car.slug}}">
                </div>
                <div class="form_attribute_container half">
                    <span>Year*</span>
                    <input type="number" name="year" required id="id_year"  value="{{car.year}}">
                </div>
                <div class="form_attribute_container half">
                    <span>Run*</span>
                    <input type="number" name="run" required id="id_run" value="{{car.run}}">
                </div>
                <div class="form_attribute_container half">
                    <span>Engine Capacity*</span>
                    <input type="number" name="engine_capacity" required id="id_engine_capacity"  value="{{car.engine_capacity}}">
                </div>
                <div class="form_attribute_container half">
                    <span>Color*</span>
                    <input type="text" name="color" maxlength="255" required id="id_color" value="{{car.color}}">
                </div>
                <div class="form_attribute_container half">
                    <span>City*</span>
                    {{form.city}}
                </div>
                <div class="form_attribute_container half">
                    <span>Brand*</span>
                    {{form.brand}}
                </div>
                <div class="form_attribute_container half">
                    <span>Price*</span>
                    <input type="number" name="price" required id="id_price"  value="{{car.price}}">
                </div>
                <div class="form_attribute_container half">
                    <span>Main Image*</span>
                    <label for="id_main_image">Choose Image</label>
                    <input type="file" name="main_image" accept="image/*" required id="id_main_image"  value="{{car.image}}">
                </div>
                <div class="full description_container">
                    <span>Description*</span>
                    <textarea name="description" id="id_description" cols="0" rows="10" placeholder="Description">{{car.description}}</textarea>
                </div>
            <button type="submit">Update</button>
        </form>
    </div>

{% endblock %}